### PR TITLE
Fixes duplicate sessions multiple lengths

### LINKED ISSUE #4: Fix duplicate generated sessions with multiple lengths
## Symptoms

Duplicate sessions get generated when using multiple session lengths.

## Steps to reproduce

1. Create a session generator that extends [`AbstractSessionGenerator`]
2. Initialize it with multiple session lengths (ex. 30m and 1hr)
3. Generate sessions (ex. from 8:00 till 10:00 on a particular date)
4. Observe symptom

The examples given should result in 7 sessions being generated, but instead 11 get generated.

## Possible Cause

A previous slight change in the algorithm resulted in the algorithm generating duplicate sessions.

This is because previously, the session length iteration had a chance to terminate and return the result of a recursive call. This is no longer the case.

The result makes the `processed` list of already processed session start times no longer control whether recursion happens or not. Instead, it is just checked for whether or not to register the new start times, which may get populated with duplicate start times within the same iteration.

## Recommended solution

Populate the `processed` list at the end of the session length iteration, and check against it at the beginning of the start time iteration.

### PR DESCRIPTION
**Pull request by mecha**
Fixes #4

### CODE REVIEW

File: src/AbstractSessionGenerator.php [hunk 1]
```diff
@@ -87,23 +91,22 @@ protected function _generateRecursive(
                     if ($validator !== null) {
                         $validator->validate($session);
                     }
-                    $results[]          = $session;
-                    $processed[$_start] = true;
+                    $results[] = $session;
```
Comment (XedinUnknown) [inline src/AbstractSessionGenerator.php:94]: At first, thought this may have an undesirable memory footprint. Then realized that the session object is shared, and is already "cached" in this scope. Good job!

**Review by XedinUnknown — APPROVED** [review]
